/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.I2GroceryStore;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.ImageFilter;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.ListModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ph
 */

public class I2GroceryStoreUI extends javax.swing.JFrame {
    final private ArrayList<Pair<String>> managers = new ArrayList<>(1);
    final private ArrayList<Pair<String>> cashiers = new ArrayList<>(1);
    final private ArrayList<JLabel> images = new ArrayList<>(2);
    private int currentUser = -1;
    private boolean hasManager = false;
    private int LastUserNum = 0;
   /**
    * Creates new form I2GroceryStoreUI
    */
   public I2GroceryStoreUI() {
      initComponents();
      setNoneVisible();
      clearMessages();
      mainPanel.setVisible(true);
      //for testing purposes
      managers.add(new Pair<>("admin", "password"));
      cashiers.add(new Pair<>("test", "password"));
      images.add(new JLabel("No Image"));
      images.add(new JLabel("No Image"));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        signInPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameEntry = new javax.swing.JTextField();
        passwordEntry = new javax.swing.JPasswordField();
        cashierSignIn = new javax.swing.JButton();
        ManagerSignIn = new javax.swing.JButton();
        signInTitle = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        invalidCredentialsMessage = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 14), new java.awt.Dimension(0, 14), new java.awt.Dimension(32767, 14));
        cashierPanel = new javax.swing.JPanel();
        cashierCheckout = new javax.swing.JButton();
        cashierProfile = new javax.swing.JButton();
        cashierLogOut = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        managerPanel = new javax.swing.JPanel();
        managerCheckout = new javax.swing.JButton();
        managerLogOut = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();
        managerProfile = new javax.swing.JButton();
        updateProductSuccessMessage = new javax.swing.JTextField();
        newProductSuccessMessage = new javax.swing.JTextField();
        jTextArea3 = new javax.swing.JTextArea();
        updateProductPanel = new javax.swing.JPanel();
        updateProductTitle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        confirmUpdate = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        profileTitle = new javax.swing.JTextField();
        editPicture = new javax.swing.JLabel();
        profileChanges = new javax.swing.JButton();
        ChangeProfilePhotoButton = new javax.swing.JButton();
        managerProfilePanel = new javax.swing.JPanel();
        OtherAccountsLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ManDeleteProfileButton = new javax.swing.JButton();
        ManPromoteProfileButton = new javax.swing.JButton();
        ManCreateProfileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManProfileList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(704, 0), new java.awt.Dimension(704, 0), new java.awt.Dimension(704, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 227), new java.awt.Dimension(0, 227), new java.awt.Dimension(32767, 227));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(255, 0), new java.awt.Dimension(255, 0), new java.awt.Dimension(204, 32767));
        jPanel1 = new javax.swing.JPanel();
        passwordField = new javax.swing.JTextField();
        editPassword = new javax.swing.JLabel();
        editUserName = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        profilePicturePanel = new javax.swing.JPanel();
        addProductPanel = new javax.swing.JPanel();
        addProductTitle1 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        NumAvail = new javax.swing.JLabel();
        VendorID = new javax.swing.JLabel();
        VendorPhone = new javax.swing.JLabel();
        addCancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        RequiredLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        NumAvailField = new javax.swing.JTextField();
        VendorField = new javax.swing.JTextField();
        OptionalLabel = new javax.swing.JLabel();
        VendorPhoneField = new javax.swing.JFormattedTextField();
        NewProductBarcodeNum = new javax.swing.JLabel();
        addExitButton = new javax.swing.JButton();
        PriceField = new javax.swing.JTextField();
        confirmNotice = new javax.swing.JLabel();
        checkoutPanel = new javax.swing.JPanel();
        mainTitle1 = new javax.swing.JTextField();
        checkoutTablePane = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        ManualBarcodeField = new javax.swing.JTextField();
        ManualBarcode = new javax.swing.JLabel();
        ManualBarcodeButton = new javax.swing.JButton();
        CheckoutButton = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        TotalNum = new javax.swing.JLabel();
        barcodeNotFoundMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1117, 610));
        setMinimumSize(new java.awt.Dimension(1117, 610));
        setPreferredSize(new java.awt.Dimension(1117, 610));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1117, 610));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1117, 610));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1117, 610));

        mainPanel.setAlignmentX(0.0F);
        mainPanel.setAlignmentY(0.0F);
        mainPanel.setMaximumSize(new java.awt.Dimension(1117, 610));
        mainPanel.setMinimumSize(new java.awt.Dimension(1117, 610));
        mainPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        exit.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        signIn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        signIn.setText("Sign In");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Store Management System");
        jTextArea1.setFocusable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        signInPanel.setAlignmentX(0.0F);
        signInPanel.setAlignmentY(0.0F);
        signInPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        userLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        userLabel.setText("User Name:");

        passwordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        passwordLabel.setText("Password:");

        cashierSignIn.setText("Sign in as Cashier");
        cashierSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierSignInActionPerformed(evt);
            }
        });

        ManagerSignIn.setText("Sign in as Manager");
        ManagerSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerSignInActionPerformed(evt);
            }
        });

        signInTitle.setEditable(false);
        signInTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        signInTitle.setText("Sign In");
        signInTitle.setFocusable(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        invalidCredentialsMessage.setForeground(new java.awt.Color(255, 0, 51));
        invalidCredentialsMessage.setText("Invalid credentials for the selected role.");
        invalidCredentialsMessage.setFocusable(false);

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabel)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signInPanelLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(cancelButton))
                            .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signInPanelLayout.createSequentialGroup()
                                    .addGap(104, 104, 104)
                                    .addComponent(invalidCredentialsMessage)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signInPanelLayout.createSequentialGroup()
                                    .addComponent(cashierSignIn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ManagerSignIn))
                                .addComponent(passwordEntry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(userLabel)
                .addGap(18, 18, 18)
                .addComponent(userNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(passwordLabel)
                .addGap(18, 18, 18)
                .addComponent(passwordEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashierSignIn)
                            .addComponent(ManagerSignIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(invalidCredentialsMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        cashierPanel.setAlignmentX(0.0F);
        cashierPanel.setAlignmentY(0.0F);
        cashierPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        cashierCheckout.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cashierCheckout.setText("Checkout");
        cashierCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckoutActionPerformed(evt);
            }
        });

        cashierProfile.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cashierProfile.setText("Profile Settings");
        cashierProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierProfileActionPerformed(evt);
            }
        });

        cashierLogOut.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cashierLogOut.setText("Log Out");
        cashierLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierLogOutActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\t                 Store Management System");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setFocusable(false);

        javax.swing.GroupLayout cashierPanelLayout = new javax.swing.GroupLayout(cashierPanel);
        cashierPanel.setLayout(cashierPanelLayout);
        cashierPanelLayout.setHorizontalGroup(
            cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashierPanelLayout.createSequentialGroup()
                        .addComponent(cashierCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashierProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashierLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 354, Short.MAX_VALUE))
                    .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        cashierPanelLayout.setVerticalGroup(
            cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashierPanelLayout.createSequentialGroup()
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cashierCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cashierPanelLayout.createSequentialGroup()
                        .addComponent(cashierProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cashierLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        managerPanel.setAlignmentX(0.0F);
        managerPanel.setAlignmentY(0.0F);
        managerPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        managerCheckout.setText("Checkout");
        managerCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerCheckoutActionPerformed(evt);
            }
        });

        managerLogOut.setText("Log Out");
        managerLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLogOutActionPerformed(evt);
            }
        });

        addProduct.setText("Add Product");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        updateProduct.setText("Update Existing Product");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        managerProfile.setText("Edit Profile");
        managerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerProfileActionPerformed(evt);
            }
        });

        updateProductSuccessMessage.setEditable(false);
        updateProductSuccessMessage.setText("                                                                        Product Successfully Updated");
        updateProductSuccessMessage.setFocusable(false);

        newProductSuccessMessage.setEditable(false);
        newProductSuccessMessage.setText("                                                                     New Product Successfully Added");
        newProductSuccessMessage.setFocusable(false);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\t                    Store Management System");
        jTextArea3.setFocusable(false);

        javax.swing.GroupLayout managerPanelLayout = new javax.swing.GroupLayout(managerPanel);
        managerPanel.setLayout(managerPanelLayout);
        managerPanelLayout.setHorizontalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerPanelLayout.createSequentialGroup()
                        .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managerCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managerLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(managerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(managerPanelLayout.createSequentialGroup()
                        .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newProductSuccessMessage, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextArea3))
                        .addContainerGap())
                    .addGroup(managerPanelLayout.createSequentialGroup()
                        .addComponent(updateProductSuccessMessage)
                        .addContainerGap())))
        );
        managerPanelLayout.setVerticalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelLayout.createSequentialGroup()
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managerCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(updateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managerProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managerLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(newProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        updateProductPanel.setAlignmentX(0.0F);
        updateProductPanel.setAlignmentY(0.0F);
        updateProductPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        updateProductTitle.setEditable(false);
        updateProductTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        updateProductTitle.setText("                                Update Existing Product");
        updateProductTitle.setFocusable(false);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Apples", "00001",  new Integer(30), "$0.99", "12", "465-676-8642"},
                {"Oranges", "00002",  new Integer(20), "$1.50", "15", "465-649-5413"},
                {"Bananas", "00003",  new Integer(40), "$0.95", "09", "646-658-6492"},
                {"Plums", "00004",  new Integer(15), "$1.25", "21", "464-821-9324"},
                {"Peaches", "00005",  new Integer(20), "$1.29", "05", "464-132-8972"}
            },
            new String [] {
                "Name", "Barcode Number", "Number Available", "Price per Unit", "Vendor Number", "Vendor Contact #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
            productTable.getColumnModel().getColumn(4).setResizable(false);
            productTable.getColumnModel().getColumn(5).setResizable(false);
        }

        confirmUpdate.setText("Confirm Changes");
        confirmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateProductPanelLayout = new javax.swing.GroupLayout(updateProductPanel);
        updateProductPanel.setLayout(updateProductPanelLayout);
        updateProductPanelLayout.setHorizontalGroup(
            updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProductTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProductPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updateProductPanelLayout.setVerticalGroup(
            updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProductPanelLayout.createSequentialGroup()
                .addComponent(updateProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(confirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        profilePanel.setAlignmentX(0.0F);
        profilePanel.setAlignmentY(0.0F);
        profilePanel.setMaximumSize(new java.awt.Dimension(1117, 610));
        profilePanel.setMinimumSize(new java.awt.Dimension(1117, 610));
        profilePanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        profileTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        profileTitle.setText("Edit Your Profile");

        editPicture.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        editPicture.setText("Profile Picture:");

        profileChanges.setText("Save Changes");
        profileChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileChangesActionPerformed(evt);
            }
        });

        ChangeProfilePhotoButton.setText("New Photo");
        ChangeProfilePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeProfilePhotoButtonActionPerformed(evt);
            }
        });

        OtherAccountsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OtherAccountsLabel.setText("Other Accounts");

        ManDeleteProfileButton.setText("Delete");
        ManDeleteProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManDeleteProfileButtonActionPerformed(evt);
            }
        });

        ManPromoteProfileButton.setText("Promote");
        ManPromoteProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManPromoteProfileButtonActionPerformed(evt);
            }
        });

        ManCreateProfileButton.setText("Create");
        ManCreateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManCreateProfileButtonActionPerformed(evt);
            }
        });

        ManProfileList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ManProfileList);
        if (ManProfileList.getColumnModel().getColumnCount() > 0) {
            ManProfileList.getColumnModel().getColumn(0).setResizable(false);
            ManProfileList.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("\"password\" is the default Password");

        javax.swing.GroupLayout managerProfilePanelLayout = new javax.swing.GroupLayout(managerProfilePanel);
        managerProfilePanel.setLayout(managerProfilePanelLayout);
        managerProfilePanelLayout.setHorizontalGroup(
            managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerProfilePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(managerProfilePanelLayout.createSequentialGroup()
                        .addGroup(managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managerProfilePanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ManPromoteProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(ManDeleteProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ManCreateProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(OtherAccountsLabel))
                        .addContainerGap())))
        );
        managerProfilePanelLayout.setVerticalGroup(
            managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerProfilePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(OtherAccountsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerProfilePanelLayout.createSequentialGroup()
                        .addGroup(managerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManCreateProfileButton)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManDeleteProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManPromoteProfileButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passwordField.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        editPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        editPassword.setText("Password:");

        editUserName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        editUserName.setText("User Name:");

        userNameField.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("This Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editUserName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(editPassword)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editUserName)
                        .addGap(72, 72, 72))
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPassword)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profilePicturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profilePicturePanel.setMaximumSize(new java.awt.Dimension(202, 227));
        profilePicturePanel.setMinimumSize(new java.awt.Dimension(202, 227));

        javax.swing.GroupLayout profilePicturePanelLayout = new javax.swing.GroupLayout(profilePicturePanel);
        profilePicturePanel.setLayout(profilePicturePanelLayout);
        profilePicturePanelLayout.setHorizontalGroup(
            profilePicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        profilePicturePanelLayout.setVerticalGroup(
            profilePicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editPicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                                .addComponent(profilePicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ChangeProfilePhotoButton)
                            .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(profileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(379, Short.MAX_VALUE))))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managerProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editPicture)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(profilePicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeProfilePhotoButton))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(profileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addProductTitle1.setEditable(false);
        addProductTitle1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addProductTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addProductTitle1.setText("Add Product");

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setText("ID:");

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setText("Name:");

        Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Price.setText("Price per Unit:");

        NumAvail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumAvail.setText("Number Available:");

        VendorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VendorID.setText("Vendor ID:");

        VendorPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VendorPhone.setText("Vendor Phone:");

        addCancelButton.setText("Cancel Changes");
        addCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelButtonActionPerformed(evt);
            }
        });

        RequiredLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RequiredLabel.setText("Required Fields");

        NameField.setMinimumSize(new java.awt.Dimension(100, 20));

        NumAvailField.setMinimumSize(new java.awt.Dimension(100, 20));

        VendorField.setMinimumSize(new java.awt.Dimension(100, 20));

        OptionalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OptionalLabel.setText("Optional Fields");

        try {
            VendorPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        NewProductBarcodeNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewProductBarcodeNum.setText("0000000");

        addExitButton.setText("Confirm Changes");
        addExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExitButtonActionPerformed(evt);
            }
        });

        confirmNotice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        confirmNotice.setForeground(new java.awt.Color(255, 51, 51));
        confirmNotice.setText("Please fill in required fields before confirming!");

        javax.swing.GroupLayout addProductPanelLayout = new javax.swing.GroupLayout(addProductPanel);
        addProductPanel.setLayout(addProductPanelLayout);
        addProductPanelLayout.setHorizontalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addProductTitle1)
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductPanelLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(VendorPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumAvail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VendorID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(OptionalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VendorPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VendorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumAvailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(739, 739, 739))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductPanelLayout.createSequentialGroup()
                                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewProductBarcodeNum)
                                    .addGroup(addProductPanelLayout.createSequentialGroup()
                                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                        .addGap(136, 136, 136)
                                        .addComponent(confirmNotice))))
                            .addComponent(RequiredLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addProductPanelLayout.setVerticalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProductTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(RequiredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(NewProductBarcodeNum))
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price)
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OptionalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumAvail)
                            .addComponent(NumAvailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VendorID)
                            .addComponent(VendorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VendorPhone)
                            .addComponent(VendorPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(confirmNotice)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        checkoutPanel.setAlignmentX(0.0F);
        checkoutPanel.setAlignmentY(0.0F);
        checkoutPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        mainTitle1.setEditable(false);
        mainTitle1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        mainTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainTitle1.setText("Checkout");
        mainTitle1.setFocusable(false);
        mainTitle1.setRequestFocusEnabled(false);

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode Num", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkoutTable.getTableHeader().setReorderingAllowed(false);
        checkoutTablePane.setViewportView(checkoutTable);

        ManualBarcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ManualBarcode.setText("Manual Barcode Entry:");

        ManualBarcodeButton.setText("Add");
        ManualBarcodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualBarcodeButtonActionPerformed(evt);
            }
        });

        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalLabel.setText("Total:");

        TotalNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalNum.setText("$0.00");

        barcodeNotFoundMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        barcodeNotFoundMessage.setForeground(new java.awt.Color(255, 0, 0));
        barcodeNotFoundMessage.setText("Barcode Not Found!");

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(barcodeNotFoundMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(checkoutPanelLayout.createSequentialGroup()
                                .addComponent(ManualBarcode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ManualBarcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ManualBarcodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                        .addGap(100, 100, 100))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addComponent(TotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalNum)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                        .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                        .addComponent(mainTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(463, 463, 463))))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(checkoutTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManualBarcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManualBarcode)
                            .addComponent(ManualBarcodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barcodeNotFoundMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalNum)
                            .addComponent(TotalLabel))))
                .addGap(35, 35, 35)
                .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(signInPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cashierPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(managerPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(updateProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(profilePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(checkoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(cashierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(managerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(updateProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cashierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(managerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(updateProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void managerLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLogOutActionPerformed
      profilePicturePanel.remove(images.get(currentUser));
      currentUser = -1;
      hasManager = false;
      managerPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_managerLogOutActionPerformed

   private void managerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerProfileActionPerformed
      if(hasManager == true){
        paintProfilePic();
        populateProfileList();
        managerProfilePanel.setVisible(true);
        managerPanel.setVisible(false);
        profilePanel.setVisible(true);
      }
   }//GEN-LAST:event_managerProfileActionPerformed

   private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
      mainPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_signInActionPerformed

   private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      System.exit(0);
   }//GEN-LAST:event_exitActionPerformed

   private void cashierSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierSignInActionPerformed
        Pair<String> UserPair = new Pair<>(userNameEntry.getText(), String.valueOf(passwordEntry.getPassword()));

        for (Pair<String> cashier : cashiers) {
          if(cashier.equals(UserPair)){
            signInPanel.setVisible(false);
            cashierPanel.setVisible(true);
            clearMessages();
            currentUser = cashiers.indexOf(cashier);
            return;
          }
        }
      //if we're here, bad username/password combo
      invalidCredentialsMessage.setVisible(true);
   }//GEN-LAST:event_cashierSignInActionPerformed

   private void ManagerSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerSignInActionPerformed
       Pair<String> UserPair = new Pair<>(userNameEntry.getText(), String.valueOf(passwordEntry.getPassword())); 
       
        for (Pair<String> manager : managers) {
          if(manager.equals(UserPair)){
            signInPanel.setVisible(false);
            managerPanel.setVisible(true);
            clearMessages();
            currentUser = managers.indexOf(manager);
            hasManager = true;
            return;
          }
        }
      //if we're here, bad username/password combo
      invalidCredentialsMessage.setVisible(true);
   }//GEN-LAST:event_ManagerSignInActionPerformed

   private void cashierCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckoutActionPerformed
      cashierPanel.setVisible(false);
      checkoutPanel.setVisible(true);
   }//GEN-LAST:event_cashierCheckoutActionPerformed

   private void cashierProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierProfileActionPerformed
      paintProfilePic();
      
      managerProfilePanel.setVisible(false);
      cashierPanel.setVisible(false);
      profilePanel.setVisible(true);
   }//GEN-LAST:event_cashierProfileActionPerformed

   private void cashierLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierLogOutActionPerformed
      profilePicturePanel.remove(images.get(currentUser));
      currentUser = -1;
      cashierPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_cashierLogOutActionPerformed

   private void managerCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerCheckoutActionPerformed
      if(hasManager = true){
        managerPanel.setVisible(false);
        checkoutPanel.setVisible(true);
      }
   }//GEN-LAST:event_managerCheckoutActionPerformed

   private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
      if(hasManager == true){
        managerPanel.setVisible(false);
        addProductPanel.setVisible(true);
      }
   }//GEN-LAST:event_addProductActionPerformed

   private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
      if(hasManager == true){
        managerPanel.setVisible(false);
        updateProductPanel.setVisible(true);
      }
   }//GEN-LAST:event_updateProductActionPerformed

   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      signInPanel.setVisible(false);
      mainPanel.setVisible(true);
   }//GEN-LAST:event_cancelButtonActionPerformed

   private void confirmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateActionPerformed
      if(hasManager == true){
        updateProductPanel.setVisible(false);
        managerPanel.setVisible(true);
      }
   }//GEN-LAST:event_confirmUpdateActionPerformed

   private void profileChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileChangesActionPerformed
      managerProfilePanel.setVisible(false);
      profilePanel.setVisible(false);
      
      checkNamePassChange();
      
      userNameField.setText("");
      passwordField.setText("");
      
      if(hasManager == true)
          managerPanel.setVisible(true);
      else
          cashierPanel.setVisible(true);
   }//GEN-LAST:event_profileChangesActionPerformed

    private void addCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelButtonActionPerformed
        NameField.setText("");
        NumAvailField.setText("");
        PriceField.setText("");
        VendorField.setText("");
        VendorPhoneField.setText("");

        addProductPanel.setVisible(false);
        mainPanel.setVisible(true);
        updateProductSuccessMessage.setVisible(false);
        newProductSuccessMessage.setVisible(false);
    }//GEN-LAST:event_addCancelButtonActionPerformed

    private void addExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExitButtonActionPerformed
        if(!(NameField.getText().equals("") || PriceField.getText().equals(""))){ //required fields have text?
            DefaultTableModel tableModel = (DefaultTableModel) productTable.getModel(); //get the data structure under the JTable
            tableModel.addRow(
                new Object[]{NameField.getText(), NewProductBarcodeNum.getText(), NumAvailField.getText(), PriceField.getText(), VendorField.getText(), VendorPhoneField.getText()} //new table row
            );

            addProductPanel.setVisible(false);
            mainPanel.setVisible(true);
            updateProductSuccessMessage.setVisible(false);
            newProductSuccessMessage.setVisible(true);
        }
        else{
            confirmNotice.setVisible(true);
        }
    }//GEN-LAST:event_addExitButtonActionPerformed

    private void ManualBarcodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualBarcodeButtonActionPerformed
        DefaultTableModel checkoutTableModel = (DefaultTableModel) checkoutTable.getModel();
        String searchStr = ManualBarcodeField.getText();
        boolean found = false;

        for (int i = 0; i <= productTable.getRowCount() - 1; i++){
            if(searchStr.equals(productTable.getValueAt(i,1))){ //if entered barcode matches this row in productTable
                found = true;
                barcodeNotFoundMessage.setVisible(false);
                checkoutTableModel.addRow(
                    new Object[]{productTable.getValueAt(i,1),productTable.getValueAt(i,0),productTable.getValueAt(i,3)} //make new checkout row
                );
                TotalNum.setText("$" +
                    (Double.parseDouble(TotalNum.getText().substring(1)) + //get old total
                        Double.parseDouble(productTable.getValueAt(i,3).toString().substring(1))) //add new entry's price
                );
                break;
            }
        }
        if(!found){
            System.out.println("here");
            barcodeNotFoundMessage.setVisible(true);
        }
    }//GEN-LAST:event_ManualBarcodeButtonActionPerformed

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutButtonActionPerformed
        ((DefaultTableModel) checkoutTable.getModel()).setRowCount(0);
        ManualBarcodeField.setText("");
        TotalNum.setText("$0.00");
        checkoutPanel.setVisible(false);
        mainPanel.setVisible(true);
    }//GEN-LAST:event_CheckoutButtonActionPerformed

    private void ManPromoteProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManPromoteProfileButtonActionPerformed
        int[] toProm = ManProfileList.getSelectedRows();
        
        for(int index : toProm){
            if(index >= managers.size()){ //can't promote a manager...
                index -= managers.size();
                Pair user = cashiers.get(index);
                cashiers.remove(index);
                managers.add(user);
            }
        }
        populateProfileList();
    }//GEN-LAST:event_ManPromoteProfileButtonActionPerformed

    private void ManCreateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManCreateProfileButtonActionPerformed
        cashiers.add(new Pair<>(String.valueOf(LastUserNum), "password")); //create a new user with a user number and default password
        LastUserNum++;
        populateProfileList();
    }//GEN-LAST:event_ManCreateProfileButtonActionPerformed

    private void ManDeleteProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManDeleteProfileButtonActionPerformed
        int[] toDelete = ManProfileList.getSelectedRows();
        
        for(int index : toDelete){
            if(index == currentUser) continue; //can't delete yourself...
            
            if(index >= managers.size()){
                index -= managers.size();
                images.remove(index);
                cashiers.remove(index);
            }
            else{
                images.remove(index);
                managers.remove(index);
            }
        }
        populateProfileList();
    }//GEN-LAST:event_ManDeleteProfileButtonActionPerformed

    private void ChangeProfilePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeProfilePhotoButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        final FileFilter JPGFilter = new FileNameExtensionFilter(
                "JPG Files", "jpg");
        fc.setFileFilter(JPGFilter);
        fc.setAcceptAllFileFilterUsed(false);
        int retval = fc.showOpenDialog(null);
        
        if(retval == JFileChooser.APPROVE_OPTION){
            File image = fc.getSelectedFile();
            JLabel profilePicLabel = processImage(image);
            if(hasManager){
                images.set(currentUser, profilePicLabel);
            }
            else{
                images.set(currentUser+managers.size(), profilePicLabel);
            }
        }
        
        paintProfilePic();
    }//GEN-LAST:event_ChangeProfilePhotoButtonActionPerformed
    private void paintProfilePic() {
      profilePicturePanel.removeAll();
      
      if(hasManager){
          profilePicturePanel.add(images.get(currentUser));
      }
      else{
          profilePicturePanel.add(images.get(currentUser+managers.size()));
      }
      FlowLayout layout = new FlowLayout();
      layout.setVgap(-1);
      profilePicturePanel.setLayout(layout);
      
      profilePicturePanel.revalidate();
      profilePicturePanel.repaint();
      profilePanel.add(profilePicturePanel);
      profilePanel.repaint();
    }
    
    private JLabel processImage(File image) { //turns the image into a JLabel Element of the right size.
        JLabel profilePicLabel = new JLabel("Bad Image");
        try {
            BufferedImage profilePic = ImageIO.read(image);
            BufferedImage temp = new BufferedImage(202, 227, profilePic.getType());
            Graphics2D g2d = temp.createGraphics();
            g2d.drawImage(profilePic, 0, 0, 202, 227, null);
            profilePic = temp;
            g2d.dispose();
            ImageIcon icon = new ImageIcon(profilePic);
            profilePicLabel= new JLabel(icon);
        } catch (IOException ex) {
            Logger.getLogger(I2GroceryStoreUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return profilePicLabel;
    }
    
   private void setNoneVisible(){
       profilePanel.setVisible(false);
       updateProductPanel.setVisible(false);
       signInPanel.setVisible(false);
       managerPanel.setVisible(false);
       cashierPanel.setVisible(false);
       mainPanel.setVisible(false);
       addProductPanel.setVisible(false);
       checkoutPanel.setVisible(false);
   }
    
   private void clearMessages(){
       newProductSuccessMessage.setVisible(false);
       updateProductSuccessMessage.setVisible(false);
       invalidCredentialsMessage.setVisible(false);
       barcodeNotFoundMessage.setVisible(false);
    }
   
    private void checkNamePassChange() {
      String newName = userNameField.getText();
      String newPass = passwordField.getText();
      if(!(newName.equals(""))){
          String oldPass;
          if(hasManager){
              oldPass = managers.get(currentUser).getValue();
              managers.set(currentUser, new Pair<>(newName, oldPass));
          }
          else{
              oldPass = cashiers.get(currentUser).getValue();
              cashiers.set(currentUser, new Pair<>(newName, oldPass));
          }
      }
      if(!(newPass.equals(""))){
          String oldName;
          if(hasManager){
              oldName = managers.get(currentUser).getKey();
              managers.set(currentUser, new Pair<>(oldName, newPass));
          }
          else{
              oldName = cashiers.get(currentUser).getKey();
              cashiers.set(currentUser, new Pair<>(oldName, newPass));
          }
      }
    }
   
   private void populateProfileList() {
        ((DefaultTableModel) ManProfileList.getModel()).setRowCount(0);
        DefaultTableModel profileList = (DefaultTableModel) ManProfileList.getModel();
        for(Pair<String> manager : managers){
            profileList.addRow(
                new Object[]{manager.getKey(),"Manager"}
            );
        }
        for(Pair<String> cashier : cashiers){
            profileList.addRow(
                new Object[]{cashier.getKey(),"Cashier"}
            );
        }
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
   
      /* Create and display the form */
      java.awt.EventQueue.invokeLater(
         new Runnable() {
            @Override
            public void run() {
               new I2GroceryStoreUI().setVisible(true);
            }
         });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeProfilePhotoButton;
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JLabel ID;
    private javax.swing.JButton ManCreateProfileButton;
    private javax.swing.JButton ManDeleteProfileButton;
    private javax.swing.JTable ManProfileList;
    private javax.swing.JButton ManPromoteProfileButton;
    private javax.swing.JButton ManagerSignIn;
    private javax.swing.JLabel ManualBarcode;
    private javax.swing.JButton ManualBarcodeButton;
    private javax.swing.JTextField ManualBarcodeField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NewProductBarcodeNum;
    private javax.swing.JLabel NumAvail;
    private javax.swing.JTextField NumAvailField;
    private javax.swing.JLabel OptionalLabel;
    private javax.swing.JLabel OtherAccountsLabel;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceField;
    private javax.swing.JLabel RequiredLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalNum;
    private javax.swing.JTextField VendorField;
    private javax.swing.JLabel VendorID;
    private javax.swing.JLabel VendorPhone;
    private javax.swing.JFormattedTextField VendorPhoneField;
    private javax.swing.JButton addCancelButton;
    private javax.swing.JButton addExitButton;
    private javax.swing.JButton addProduct;
    private javax.swing.JPanel addProductPanel;
    private javax.swing.JTextField addProductTitle1;
    private javax.swing.JLabel barcodeNotFoundMessage;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cashierCheckout;
    private javax.swing.JButton cashierLogOut;
    private javax.swing.JPanel cashierPanel;
    private javax.swing.JButton cashierProfile;
    private javax.swing.JButton cashierSignIn;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JScrollPane checkoutTablePane;
    private javax.swing.JLabel confirmNotice;
    private javax.swing.JButton confirmUpdate;
    private javax.swing.JLabel editPassword;
    private javax.swing.JLabel editPicture;
    private javax.swing.JLabel editUserName;
    private javax.swing.JButton exit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel invalidCredentialsMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mainTitle1;
    private javax.swing.JButton managerCheckout;
    private javax.swing.JButton managerLogOut;
    private javax.swing.JPanel managerPanel;
    private javax.swing.JButton managerProfile;
    private javax.swing.JPanel managerProfilePanel;
    private javax.swing.JTextField newProductSuccessMessage;
    private javax.swing.JPasswordField passwordEntry;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTable productTable;
    private javax.swing.JButton profileChanges;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profilePicturePanel;
    private javax.swing.JTextField profileTitle;
    private javax.swing.JButton signIn;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JTextField signInTitle;
    private javax.swing.JButton updateProduct;
    private javax.swing.JPanel updateProductPanel;
    private javax.swing.JTextField updateProductSuccessMessage;
    private javax.swing.JTextField updateProductTitle;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userNameEntry;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables



    
}