import javax.swing.table.*;


/**
 *
 * @author Hashill Patel
 * @author Chris Dumas
 * 
 */
public class systemUI extends javax.swing.JFrame {

    /**
     * Creates new form systemUI
     */
    public systemUI() {
        initComponents();
        mainPanel.setVisible(true);
        updateProductPanel.setVisible(false);
        checkoutPanel.setVisible(false);
        addProductPanel.setVisible(false);
        newProductSuccessMessage.setVisible(false);
        updateProductSuccessMessage.setVisible(false);
        barcodeNotFoundMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        checkoutButton = new javax.swing.JButton();
        showAddScreenButton = new javax.swing.JButton();
        mainTitle = new javax.swing.JTextField();
        showUpdateScreenButton = new javax.swing.JButton();
        newProductSuccessMessage = new javax.swing.JTextField();
        updateProductSuccessMessage = new javax.swing.JTextField();
        addProductPanel = new javax.swing.JPanel();
        addProductTitle = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        NumAvail = new javax.swing.JLabel();
        VendorID = new javax.swing.JLabel();
        VendorPhone = new javax.swing.JLabel();
        addCancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        RequiredLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        NumAvailField = new javax.swing.JTextField();
        VendorField = new javax.swing.JTextField();
        OptionalLabel = new javax.swing.JLabel();
        VendorPhoneField = new javax.swing.JFormattedTextField();
        NewProductBarcodeNum = new javax.swing.JLabel();
        addExitButton = new javax.swing.JButton();
        PriceField = new javax.swing.JTextField();
        confirmNotice = new javax.swing.JLabel();
        updateProductPanel = new javax.swing.JPanel();
        productTablePane = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        updateProductTitle = new javax.swing.JTextField();
        updateExitButton = new javax.swing.JButton();
        checkoutPanel = new javax.swing.JPanel();
        mainTitle1 = new javax.swing.JTextField();
        checkoutTablePane = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        ManualBarcodeField = new javax.swing.JTextField();
        ManualBarcode = new javax.swing.JLabel();
        ManualBarcodeButton = new javax.swing.JButton();
        CheckoutButton = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        TotalNum = new javax.swing.JLabel();
        barcodeNotFoundMessage = new javax.swing.JLabel();

        jPanel2.setPreferredSize(new java.awt.Dimension(1117, 610));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        showAddScreenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showAddScreenButton.setText("Add Product");
        showAddScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAddScreenButtonActionPerformed(evt);
            }
        });

        mainTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        mainTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainTitle.setText("Store Management System");

        showUpdateScreenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showUpdateScreenButton.setText("Update Existing Product");
        showUpdateScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUpdateScreenButtonActionPerformed(evt);
            }
        });

        newProductSuccessMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newProductSuccessMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newProductSuccessMessage.setText("New Product Successfullly added");

        updateProductSuccessMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateProductSuccessMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updateProductSuccessMessage.setText("Product Successfully Updated");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showUpdateScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(showAddScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addComponent(updateProductSuccessMessage)
            .addComponent(newProductSuccessMessage)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(showAddScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showUpdateScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(updateProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(newProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        checkoutButton.getAccessibleContext().setAccessibleParent(mainPanel);

        addProductTitle.setEditable(false);
        addProductTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addProductTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addProductTitle.setText("Add Product");

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setText("ID:");

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setText("Name:");

        Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Price.setText("Price per Unit:");

        NumAvail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumAvail.setText("Number Available:");

        VendorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VendorID.setText("Vendor ID:");

        VendorPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VendorPhone.setText("Vendor Phone:");

        addCancelButton.setText("Cancel Changes");
        addCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelButtonActionPerformed(evt);
            }
        });

        RequiredLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RequiredLabel.setText("Required Fields");

        NameField.setMinimumSize(new java.awt.Dimension(100, 20));

        NumAvailField.setMinimumSize(new java.awt.Dimension(100, 20));

        VendorField.setMinimumSize(new java.awt.Dimension(100, 20));

        OptionalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OptionalLabel.setText("Optional Fields");

        try {
            VendorPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        NewProductBarcodeNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewProductBarcodeNum.setText("0000000");

        addExitButton.setText("Confirm Changes");
        addExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExitButtonActionPerformed(evt);
            }
        });

        confirmNotice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        confirmNotice.setForeground(new java.awt.Color(255, 51, 51));
        confirmNotice.setText("Please fill in required fields before confirming!");

        javax.swing.GroupLayout addProductPanelLayout = new javax.swing.GroupLayout(addProductPanel);
        addProductPanel.setLayout(addProductPanelLayout);
        addProductPanelLayout.setHorizontalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addProductTitle)
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductPanelLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(VendorPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumAvail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VendorID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(OptionalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VendorPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VendorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumAvailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(739, 739, 739))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductPanelLayout.createSequentialGroup()
                                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewProductBarcodeNum)
                                    .addGroup(addProductPanelLayout.createSequentialGroup()
                                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                        .addGap(136, 136, 136)
                                        .addComponent(confirmNotice))))
                            .addComponent(RequiredLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addProductPanelLayout.setVerticalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(RequiredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(NewProductBarcodeNum))
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price)
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OptionalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumAvail)
                            .addComponent(NumAvailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VendorID)
                            .addComponent(VendorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VendorPhone)
                            .addComponent(VendorPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(confirmNotice)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Apples", "00001",  new Integer(30), "$0.99", "12", "465-676-8642"},
                {"Oranges", "00002",  new Integer(20), "$1.50", "15", "465-649-5413"},
                {"Bananas", "00003",  new Integer(40), "$0.95", "09", "646-658-6492"},
                {"Plums", "00004",  new Integer(15), "$1.25", "21", "464-821-9324"},
                {"Peaches", "00005",  new Integer(20), "$1.29", "05", "464-132-8972"}
            },
            new String [] {
                "Name", "Barcode Number", "Number Available", "Price per Unit", "Vendor Number", "Vendor Contact Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productTablePane.setViewportView(productTable);

        updateProductTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        updateProductTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updateProductTitle.setText("Update Existing Product");

        updateExitButton.setText("Confirm Changes");
        updateExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateProductPanelLayout = new javax.swing.GroupLayout(updateProductPanel);
        updateProductPanel.setLayout(updateProductPanelLayout);
        updateProductPanelLayout.setHorizontalGroup(
            updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
                    .addComponent(updateProductTitle)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProductPanelLayout.createSequentialGroup()
                        .addGap(0, 928, Short.MAX_VALUE)
                        .addComponent(updateExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updateProductPanelLayout.setVerticalGroup(
            updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(productTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(updateExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        checkoutPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        mainTitle1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        mainTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainTitle1.setText("Checkout");

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode Num", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkoutTable.getTableHeader().setReorderingAllowed(false);
        checkoutTablePane.setViewportView(checkoutTable);

        ManualBarcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ManualBarcode.setText("Manual Barcode Entry:");

        ManualBarcodeButton.setText("Add");
        ManualBarcodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualBarcodeButtonActionPerformed(evt);
            }
        });

        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalLabel.setText("Total:");

        TotalNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalNum.setText("$0.00");

        barcodeNotFoundMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        barcodeNotFoundMessage.setForeground(new java.awt.Color(255, 0, 0));
        barcodeNotFoundMessage.setText("Barcode Not Found!");

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(barcodeNotFoundMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(checkoutPanelLayout.createSequentialGroup()
                                .addComponent(ManualBarcode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ManualBarcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ManualBarcodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                        .addGap(100, 100, 100))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addComponent(TotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalNum)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTitle1)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(checkoutTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManualBarcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManualBarcode)
                            .addComponent(ManualBarcodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barcodeNotFoundMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalNum)
                            .addComponent(TotalLabel))))
                .addGap(35, 35, 35)
                .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(updateProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(checkoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(updateProductPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(updateProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAddScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAddScreenButtonActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) productTable.getModel(); //get the data structure under the JTable
        int lastProductNum = Integer.parseInt(tableModel.getValueAt(tableModel.getRowCount()-1, 1).toString()); //get the last barcode number in the table.
        NewProductBarcodeNum.setText(String.format("%05x", (lastProductNum+1))); //set the next barcode number
        
        addProductPanel.setVisible(true);
        mainPanel.setVisible(false);
        confirmNotice.setVisible(false);
    }//GEN-LAST:event_showAddScreenButtonActionPerformed

    private void showUpdateScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUpdateScreenButtonActionPerformed
        //displays table of products to update existing product
        updateProductPanel.setVisible(true);
        mainPanel.setVisible(false);
    }//GEN-LAST:event_showUpdateScreenButtonActionPerformed

    private void updateExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateExitButtonActionPerformed
        //exits product updating table and displays success message
        updateProductPanel.setVisible(false);
        mainPanel.setVisible(true);
        updateProductSuccessMessage.setVisible(true);
    }//GEN-LAST:event_updateExitButtonActionPerformed

    private void addCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelButtonActionPerformed
        NameField.setText("");
        NumAvailField.setText("");
        PriceField.setText("");
        VendorField.setText("");
        VendorPhoneField.setText("");
        
        addProductPanel.setVisible(false);
        mainPanel.setVisible(true);
        updateProductSuccessMessage.setVisible(false);
        newProductSuccessMessage.setVisible(false);
    }//GEN-LAST:event_addCancelButtonActionPerformed

    private void addExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExitButtonActionPerformed
        if(!(NameField.getText().equals("") || PriceField.getText().equals(""))){ //required fields have text?
            DefaultTableModel tableModel = (DefaultTableModel) productTable.getModel(); //get the data structure under the JTable
            tableModel.addRow(
                    new Object[]{NameField.getText(), NewProductBarcodeNum.getText(), NumAvailField.getText(), PriceField.getText(), VendorField.getText(), VendorPhoneField.getText()} //new table row
            );
            
            addProductPanel.setVisible(false);
            mainPanel.setVisible(true);
            updateProductSuccessMessage.setVisible(false);
            newProductSuccessMessage.setVisible(true);
        }
        else{
            confirmNotice.setVisible(true);
        }
    }//GEN-LAST:event_addExitButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        mainPanel.setVisible(false);
        updateProductSuccessMessage.setVisible(false);
        newProductSuccessMessage.setVisible(false);
        checkoutPanel.setVisible(true);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutButtonActionPerformed
        ((DefaultTableModel) checkoutTable.getModel()).setRowCount(0);
        ManualBarcodeField.setText("");
        TotalNum.setText("$0.00");
        checkoutPanel.setVisible(false);
        mainPanel.setVisible(true);
    }//GEN-LAST:event_CheckoutButtonActionPerformed

    private void ManualBarcodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualBarcodeButtonActionPerformed
        DefaultTableModel checkoutTableModel = (DefaultTableModel) checkoutTable.getModel();
        String searchStr = ManualBarcodeField.getText();
        boolean found = false;

        for (int i = 0; i <= productTable.getRowCount() - 1; i++){
            if(searchStr.equals(productTable.getValueAt(i,1))){ //if entered barcode matches this row in productTable
                found = true;
                barcodeNotFoundMessage.setVisible(false);
                checkoutTableModel.addRow(
                    new Object[]{productTable.getValueAt(i,1),productTable.getValueAt(i,0),productTable.getValueAt(i,3)} //make new checkout row
                );
                TotalNum.setText("$" +
                    (Double.parseDouble(TotalNum.getText().substring(1)) + //get old total
                        Double.parseDouble(productTable.getValueAt(i,3).toString().substring(1))) //add new entry's price
                );
                break;
            }
        }
        if(!found){
            System.out.println("here");
            barcodeNotFoundMessage.setVisible(true);
        }
    }//GEN-LAST:event_ManualBarcodeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(systemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(systemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(systemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(systemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new systemUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ManualBarcode;
    private javax.swing.JButton ManualBarcodeButton;
    private javax.swing.JTextField ManualBarcodeField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NewProductBarcodeNum;
    private javax.swing.JLabel NumAvail;
    private javax.swing.JTextField NumAvailField;
    private javax.swing.JLabel OptionalLabel;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceField;
    private javax.swing.JLabel RequiredLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalNum;
    private javax.swing.JTextField VendorField;
    private javax.swing.JLabel VendorID;
    private javax.swing.JLabel VendorPhone;
    private javax.swing.JFormattedTextField VendorPhoneField;
    private javax.swing.JButton addCancelButton;
    private javax.swing.JButton addExitButton;
    private javax.swing.JPanel addProductPanel;
    private javax.swing.JTextField addProductTitle;
    private javax.swing.JLabel barcodeNotFoundMessage;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JScrollPane checkoutTablePane;
    private javax.swing.JLabel confirmNotice;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mainTitle;
    private javax.swing.JTextField mainTitle1;
    private javax.swing.JTextField newProductSuccessMessage;
    private javax.swing.JTable productTable;
    private javax.swing.JScrollPane productTablePane;
    private javax.swing.JButton showAddScreenButton;
    private javax.swing.JButton showUpdateScreenButton;
    private javax.swing.JButton updateExitButton;
    private javax.swing.JPanel updateProductPanel;
    private javax.swing.JTextField updateProductSuccessMessage;
    private javax.swing.JTextField updateProductTitle;
    // End of variables declaration//GEN-END:variables
}