/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.I2GroceryStore;

/**
 *
 * @author ph
 */
public class I2GroceryStoreUI extends javax.swing.JFrame {

   /**
    * Creates new form I2GroceryStoreUI
    */
   public I2GroceryStoreUI() {
      initComponents();
      mainPanel.setVisible(true);
      updateProductPanel.setVisible(false);
      signInPanel.setVisible(false);
      cashierPanel.setVisible(false);
      managerPanel.setVisible(false);
      checkoutPanel.setVisible(false);
      addProductPanel.setVisible(false);
      newProductSuccessMessage.setVisible(false);
      updateProductSuccessMessage.setVisible(false);
      //barcodeNotFoundMessage.setVisible(false);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
   
      jLayeredPane1 = new javax.swing.JLayeredPane();
      mainPanel = new javax.swing.JPanel();
      mainTitle = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      signIn = new javax.swing.JButton();
      exit = new javax.swing.JButton();
      signInPanel = new javax.swing.JPanel();
      userLabel = new javax.swing.JLabel();
      passwordLabel = new javax.swing.JLabel();
      userNameEntry = new javax.swing.JTextField();
      passwordEntry = new javax.swing.JPasswordField();
      cashierSignIn = new javax.swing.JButton();
      ManagerSignIn = new javax.swing.JButton();
      signInTitle = new javax.swing.JTextField();
      cancelButton = new javax.swing.JButton();
      cashierPanel = new javax.swing.JPanel();
      cashierCheckout = new javax.swing.JButton();
      mainTitle1 = new javax.swing.JScrollPane();
      jTextArea2 = new javax.swing.JTextArea();
      cashierProfile = new javax.swing.JButton();
      cashierLogOut = new javax.swing.JButton();
      managerPanel = new javax.swing.JPanel();
      mainTitle2 = new javax.swing.JScrollPane();
      jTextArea3 = new javax.swing.JTextArea();
      managerCheckout = new javax.swing.JButton();
      managerLogOut = new javax.swing.JButton();
      addProduct = new javax.swing.JButton();
      updateProduct = new javax.swing.JButton();
      managerProfile = new javax.swing.JButton();
      updateProductSuccessMessage = new javax.swing.JTextField();
      newProductSuccessMessage = new javax.swing.JTextField();
      updateProductPanel = new javax.swing.JPanel();
      updateProductTitle = new javax.swing.JTextField();
      jScrollPane3 = new javax.swing.JScrollPane();
      productTable = new javax.swing.JTable();
      confirmUpdate = new javax.swing.JButton();
      addProductPanel = new javax.swing.JPanel();
      addProductTitle = new javax.swing.JTextField();
      profilePanel = new javax.swing.JPanel();
      profileTitle = new javax.swing.JTextField();
      editUserName = new javax.swing.JLabel();
      editPicture = new javax.swing.JLabel();
      editPassword = new javax.swing.JLabel();
      userNameField = new javax.swing.JTextField();
      passwordField = new javax.swing.JTextField();
      profileChanges = new javax.swing.JButton();
      checkoutPanel = new javax.swing.JPanel();
      checkoutTitle = new javax.swing.JTextField();
   
      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
   
      mainPanel.setPreferredSize(new java.awt.Dimension(700, 374));
   
      jTextArea1.setColumns(20);
      jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      jTextArea1.setRows(5);
      jTextArea1.setText("                           Store Management System");
      mainTitle.setViewportView(jTextArea1);
   
      signIn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      signIn.setText("Sign In");
      signIn.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               signInActionPerformed(evt);
            }
         });
   
      exit.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      exit.setText("Exit");
      exit.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               exitActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
      mainPanel.setLayout(mainPanelLayout);
      mainPanelLayout.setHorizontalGroup(
         mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainTitle, javax.swing.GroupLayout.Alignment.TRAILING)
         .addGroup(mainPanelLayout.createSequentialGroup()
             .addGap(43, 43, 43)
             .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 85, Short.MAX_VALUE)
             .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(32, 32, 32))
         );
      mainPanelLayout.setVerticalGroup(
         mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(mainPanelLayout.createSequentialGroup()
             .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(193, 193, 193)
             .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
   
      userLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      userLabel.setText("User Name:");
   
      passwordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      passwordLabel.setText("Password:");
   
      userNameEntry.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               userNameEntryActionPerformed(evt);
            }
         });
   
      cashierSignIn.setText("Sign in as Cashier");
      cashierSignIn.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               cashierSignInActionPerformed(evt);
            }
         });
   
      ManagerSignIn.setText("Sign in as Manager");
      ManagerSignIn.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               ManagerSignInActionPerformed(evt);
            }
         });
   
      signInTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      signInTitle.setText("Sign In");
   
      cancelButton.setText("Cancel");
      cancelButton.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               cancelButtonActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
      signInPanel.setLayout(signInPanelLayout);
      signInPanelLayout.setHorizontalGroup(
         signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(signInPanelLayout.createSequentialGroup()
             .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(signInPanelLayout.createSequentialGroup()
                     .addGap(143, 143, 143)
                     .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(userLabel)
                         .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                             .addComponent(userNameEntry, javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(passwordEntry, javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(signInPanelLayout.createSequentialGroup()
                                 .addComponent(cashierSignIn)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                 .addComponent(ManagerSignIn)))))
                 .addGroup(signInPanelLayout.createSequentialGroup()
                     .addGap(311, 311, 311)
                     .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGroup(signInPanelLayout.createSequentialGroup()
                     .addGap(314, 314, 314)
                     .addComponent(cancelButton)))
             .addContainerGap(186, Short.MAX_VALUE))
         );
      signInPanelLayout.setVerticalGroup(
         signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(signInPanelLayout.createSequentialGroup()
             .addComponent(signInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(107, 107, 107)
             .addComponent(userLabel)
             .addGap(18, 18, 18)
             .addComponent(userNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(58, 58, 58)
             .addComponent(passwordLabel)
             .addGap(18, 18, 18)
             .addComponent(passwordEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(54, 54, 54)
             .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(cashierSignIn)
                 .addComponent(ManagerSignIn))
             .addGap(18, 18, 18)
             .addComponent(cancelButton)
             .addContainerGap(738, Short.MAX_VALUE))
         );
   
      cashierCheckout.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      cashierCheckout.setText("Checkout");
      cashierCheckout.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               cashierCheckoutActionPerformed(evt);
            }
         });
   
      jTextArea2.setColumns(20);
      jTextArea2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      jTextArea2.setRows(5);
      jTextArea2.setText("                        Store Management System");
      mainTitle1.setViewportView(jTextArea2);
   
      cashierProfile.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      cashierProfile.setText("Profile Settings");
      cashierProfile.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               cashierProfileActionPerformed(evt);
            }
         });
   
      cashierLogOut.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
      cashierLogOut.setText("Log Out");
      cashierLogOut.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               cashierLogOutActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout cashierPanelLayout = new javax.swing.GroupLayout(cashierPanel);
      cashierPanel.setLayout(cashierPanelLayout);
      cashierPanelLayout.setHorizontalGroup(
         cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cashierPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(cashierPanelLayout.createSequentialGroup()
                     .addComponent(cashierCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(142, 142, 142)
                     .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(cashierProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cashierLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGap(0, 709, Short.MAX_VALUE))
                 .addComponent(mainTitle1))
             .addGap(41, 41, 41))
         );
      cashierPanelLayout.setVerticalGroup(
         cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cashierPanelLayout.createSequentialGroup()
             .addComponent(mainTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(68, 68, 68)
             .addGroup(cashierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(cashierCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGroup(cashierPanelLayout.createSequentialGroup()
                     .addComponent(cashierProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(cashierLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
             .addContainerGap(849, Short.MAX_VALUE))
         );
   
      jTextArea3.setColumns(20);
      jTextArea3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      jTextArea3.setRows(5);
      jTextArea3.setText("                               Store Management System");
      mainTitle2.setViewportView(jTextArea3);
   
      managerCheckout.setText("Checkout");
      managerCheckout.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               managerCheckoutActionPerformed(evt);
            }
         });
   
      managerLogOut.setText("Log Out");
      managerLogOut.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               managerLogOutActionPerformed(evt);
            }
         });
   
      addProduct.setText("Add Product");
      addProduct.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               addProductActionPerformed(evt);
            }
         });
   
      updateProduct.setText("Update Existing Product");
      updateProduct.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               updateProductActionPerformed(evt);
            }
         });
   
      managerProfile.setText("Edit Profile");
      managerProfile.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               managerProfileActionPerformed(evt);
            }
         });
   
      updateProductSuccessMessage.setText("                                                                        Product Successfully Updated");
   
      newProductSuccessMessage.setText("                                                                     New Product Successfully Added");
      newProductSuccessMessage.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               newProductSuccessMessageActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout managerPanelLayout = new javax.swing.GroupLayout(managerPanel);
      managerPanel.setLayout(managerPanelLayout);
      managerPanelLayout.setHorizontalGroup(
         managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPanelLayout.createSequentialGroup()
             .addGap(25, 25, 25)
             .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(managerCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(managerLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(updateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                 .addComponent(managerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGap(76, 76, 76))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(newProductSuccessMessage)
             .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(updateProductSuccessMessage)
             .addContainerGap())
         );
      managerPanelLayout.setVerticalGroup(
         managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(managerPanelLayout.createSequentialGroup()
             .addComponent(mainTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(18, 18, 18)
             .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(managerCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                 .addComponent(updateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGap(18, 18, 18)
             .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                 .addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                 .addComponent(managerProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGap(18, 18, 18)
             .addComponent(managerLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(18, 18, 18)
             .addComponent(updateProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(newProductSuccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(277, Short.MAX_VALUE))
         );
   
      updateProductTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      updateProductTitle.setText("                                Update Existing Product");
      updateProductTitle.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               updateProductTitleActionPerformed(evt);
            }
         });
   
      productTable.setModel(
         new javax.swing.table.DefaultTableModel(
         new Object [][] {
             {"Apples", "00001",  new Integer(30), "$0.99", "12", "465-676-8642"},
             {"Oranges", "00002",  new Integer(20), "$1.50", "15", "465-649-5413"},
             {"Bananas", "00003",  new Integer(40), "$0.95", "09", "646-658-6492"},
             {"Plums", "00004",  new Integer(15), "$1.25", "21", "464-821-9324"},
             {"Peaches", "00005",  new Integer(20), "$1.29", "05", "464-132-8972"}
         },
         new String [] {
             "Name", "Barcode Number", "Number Available", "Price per Unit", "Vendor Number", "Vendor Contact #"
         }
         ) {
            Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
         
            public Class getColumnClass(int columnIndex) {
               return types [columnIndex];
            }
         });
      jScrollPane3.setViewportView(productTable);
      if (productTable.getColumnModel().getColumnCount() > 0) {
         productTable.getColumnModel().getColumn(0).setResizable(false);
         productTable.getColumnModel().getColumn(1).setResizable(false);
         productTable.getColumnModel().getColumn(2).setResizable(false);
         productTable.getColumnModel().getColumn(3).setResizable(false);
         productTable.getColumnModel().getColumn(4).setResizable(false);
         productTable.getColumnModel().getColumn(5).setResizable(false);
      }
   
      confirmUpdate.setText("Confirm Changes");
      confirmUpdate.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               confirmUpdateActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout updateProductPanelLayout = new javax.swing.GroupLayout(updateProductPanel);
      updateProductPanel.setLayout(updateProductPanelLayout);
      updateProductPanelLayout.setHorizontalGroup(
         updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(updateProductPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(updateProductTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                 .addComponent(jScrollPane3)
                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProductPanelLayout.createSequentialGroup()
                     .addGap(0, 0, Short.MAX_VALUE)
                     .addComponent(confirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
             .addContainerGap())
         );
      updateProductPanelLayout.setVerticalGroup(
         updateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(updateProductPanelLayout.createSequentialGroup()
             .addComponent(updateProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(151, 151, 151)
             .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
             .addComponent(confirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(20, 20, 20))
         );
   
      addProductTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      addProductTitle.setText("                          Add Product");
      addProductTitle.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               addProductTitleActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout addProductPanelLayout = new javax.swing.GroupLayout(addProductPanel);
      addProductPanel.setLayout(addProductPanelLayout);
      addProductPanelLayout.setHorizontalGroup(
         addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(addProductTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
             .addContainerGap())
         );
      addProductPanelLayout.setVerticalGroup(
         addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(addProductPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(addProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(528, Short.MAX_VALUE))
         );
   
      profileTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      profileTitle.setText("                      Edit Your Profile");
   
      editUserName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      editUserName.setText("User Name:");
   
      editPicture.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      editPicture.setText("Profile Picture:");
   
      editPassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      editPassword.setText("Password:");
   
      userNameField.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
   
      passwordField.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
      passwordField.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               passwordFieldActionPerformed(evt);
            }
         });
   
      profileChanges.setText("Save Changes");
      profileChanges.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               profileChangesActionPerformed(evt);
            }
         });
   
      javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
      profilePanel.setLayout(profilePanelLayout);
      profilePanelLayout.setHorizontalGroup(
         profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(profilePanelLayout.createSequentialGroup()
             .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(profileTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
                 .addGroup(profilePanelLayout.createSequentialGroup()
                     .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(profilePanelLayout.createSequentialGroup()
                             .addGap(48, 48, 48)
                             .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                 .addComponent(editPicture)
                                 .addComponent(editUserName)))
                         .addGroup(profilePanelLayout.createSequentialGroup()
                             .addGap(96, 96, 96)
                             .addComponent(editPassword)))
                     .addGap(18, 18, 18)
                     .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGap(0, 0, Short.MAX_VALUE)))
             .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
             .addGap(0, 0, Short.MAX_VALUE)
             .addComponent(profileChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(36, 36, 36))
         );
      profilePanelLayout.setVerticalGroup(
         profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(profilePanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(profileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(101, 101, 101)
             .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(editUserName)
                 .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
             .addGap(70, 70, 70)
             .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(editPassword)
                 .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
             .addGap(87, 87, 87)
             .addComponent(editPicture)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
             .addComponent(profileChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(32, 32, 32))
         );
   
      checkoutTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      checkoutTitle.setText("                              Checkout");
   
      javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
      checkoutPanel.setLayout(checkoutPanelLayout);
      checkoutPanelLayout.setHorizontalGroup(
         checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(checkoutTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
             .addContainerGap())
         );
      checkoutPanelLayout.setVerticalGroup(
         checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(checkoutPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(checkoutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addContainerGap(531, Short.MAX_VALUE))
         );
   
      jLayeredPane1.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(signInPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(cashierPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(managerPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(updateProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(addProductPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(profilePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
      jLayeredPane1.setLayer(checkoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
   
      javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
      jLayeredPane1.setLayout(jLayeredPane1Layout);
      jLayeredPane1Layout.setHorizontalGroup(
         jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(cashierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(3, 3, 3)
                 .addComponent(managerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(706, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(717, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(updateProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(703, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(358, 358, 358)
                 .addComponent(addProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(350, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(703, 703, 703)
                 .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(699, 699, 699)
                 .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(700, Short.MAX_VALUE)))
         );
      jLayeredPane1Layout.setVerticalGroup(
         jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1267, Short.MAX_VALUE)
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(cashierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(207, 207, 207)
                 .addComponent(managerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addGap(207, 207, 207)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addContainerGap()))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addComponent(updateProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(0, 777, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(448, 448, 448)
                 .addComponent(addProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(238, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(671, 671, 671)
                 .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
         .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jLayeredPane1Layout.createSequentialGroup()
                 .addGap(583, 583, 583)
                 .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(584, Short.MAX_VALUE)))
         );
   
      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(0, 0, Short.MAX_VALUE))
         );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addGap(0, 0, Short.MAX_VALUE))
         );
   
      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void managerLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLogOutActionPerformed
      managerPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_managerLogOutActionPerformed

   private void managerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerProfileActionPerformed
      managerPanel.setVisible(false);
      profilePanel.setVisible(true);
   }//GEN-LAST:event_managerProfileActionPerformed

   private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
      mainPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_signInActionPerformed

   private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      System.exit(0);
   }//GEN-LAST:event_exitActionPerformed

   private void userNameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameEntryActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_userNameEntryActionPerformed

   private void updateProductTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductTitleActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_updateProductTitleActionPerformed

   private void newProductSuccessMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductSuccessMessageActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_newProductSuccessMessageActionPerformed

   private void addProductTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductTitleActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_addProductTitleActionPerformed

   private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_passwordFieldActionPerformed

   private void cashierSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierSignInActionPerformed
      signInPanel.setVisible(false);
      cashierPanel.setVisible(true);
   }//GEN-LAST:event_cashierSignInActionPerformed

   private void ManagerSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerSignInActionPerformed
      signInPanel.setVisible(false);
      managerPanel.setVisible(true);
   }//GEN-LAST:event_ManagerSignInActionPerformed

   private void cashierCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckoutActionPerformed
      cashierPanel.setVisible(false);
      checkoutPanel.setVisible(true);
   }//GEN-LAST:event_cashierCheckoutActionPerformed

   private void cashierProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierProfileActionPerformed
      cashierPanel.setVisible(false);
      profilePanel.setVisible(true);
   }//GEN-LAST:event_cashierProfileActionPerformed

   private void cashierLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierLogOutActionPerformed
      cashierPanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_cashierLogOutActionPerformed

   private void managerCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerCheckoutActionPerformed
      managerPanel.setVisible(false);
      checkoutPanel.setVisible(true);
   }//GEN-LAST:event_managerCheckoutActionPerformed

   private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
      managerPanel.setVisible(false);
      addProductPanel.setVisible(true);
   }//GEN-LAST:event_addProductActionPerformed

   private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
      managerPanel.setVisible(false);
      updateProductPanel.setVisible(true);
   }//GEN-LAST:event_updateProductActionPerformed

   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      signInPanel.setVisible(false);
      mainPanel.setVisible(true);
   }//GEN-LAST:event_cancelButtonActionPerformed

   private void confirmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateActionPerformed
      updateProductPanel.setVisible(false);
      managerPanel.setVisible(true);
      updateProductTitle.setVisible(true);
   }//GEN-LAST:event_confirmUpdateActionPerformed

   private void profileChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileChangesActionPerformed
      profilePanel.setVisible(false);
      signInPanel.setVisible(true);
   }//GEN-LAST:event_profileChangesActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(I2GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
   
      /* Create and display the form */
      java.awt.EventQueue.invokeLater(
         new Runnable() {
            public void run() {
               new I2GroceryStoreUI().setVisible(true);
            }
         });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton ManagerSignIn;
   private javax.swing.JButton addProduct;
   private javax.swing.JPanel addProductPanel;
   private javax.swing.JTextField addProductTitle;
   private javax.swing.JButton cancelButton;
   private javax.swing.JButton cashierCheckout;
   private javax.swing.JButton cashierLogOut;
   private javax.swing.JPanel cashierPanel;
   private javax.swing.JButton cashierProfile;
   private javax.swing.JButton cashierSignIn;
   private javax.swing.JPanel checkoutPanel;
   private javax.swing.JTextField checkoutTitle;
   private javax.swing.JButton confirmUpdate;
   private javax.swing.JLabel editPassword;
   private javax.swing.JLabel editPicture;
   private javax.swing.JLabel editUserName;
   private javax.swing.JButton exit;
   private javax.swing.JLayeredPane jLayeredPane1;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextArea jTextArea2;
   private javax.swing.JTextArea jTextArea3;
   private javax.swing.JPanel mainPanel;
   private javax.swing.JScrollPane mainTitle;
   private javax.swing.JScrollPane mainTitle1;
   private javax.swing.JScrollPane mainTitle2;
   private javax.swing.JButton managerCheckout;
   private javax.swing.JButton managerLogOut;
   private javax.swing.JPanel managerPanel;
   private javax.swing.JButton managerProfile;
   private javax.swing.JTextField newProductSuccessMessage;
   private javax.swing.JPasswordField passwordEntry;
   private javax.swing.JTextField passwordField;
   private javax.swing.JLabel passwordLabel;
   private javax.swing.JTable productTable;
   private javax.swing.JButton profileChanges;
   private javax.swing.JPanel profilePanel;
   private javax.swing.JTextField profileTitle;
   private javax.swing.JButton signIn;
   private javax.swing.JPanel signInPanel;
   private javax.swing.JTextField signInTitle;
   private javax.swing.JButton updateProduct;
   private javax.swing.JPanel updateProductPanel;
   private javax.swing.JTextField updateProductSuccessMessage;
   private javax.swing.JTextField updateProductTitle;
   private javax.swing.JLabel userLabel;
   private javax.swing.JTextField userNameEntry;
   private javax.swing.JTextField userNameField;
   // End of variables declaration//GEN-END:variables
}
